# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 0/2 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o main .

    - name: Generate m3u
      run: |
        chmod +x ./main
        ./main
        rm main

    - name: Commit
      run: |
        git config --local user.email "popeyelau@gmail.com"
        git config --local user.name "Popeye Lau"
        git pull
        git add .
        git commit -m "update merged.m3u"
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
